---
name: OpenTelemetry-java execution check
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        java:
          - 1.8
          - 11
          - 17
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} OS ${{ matrix.os }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run minimal parameter experiment and check success
        run: |
          ./setup.sh
          cd frameworks/OpenTelemetry-java/ 
          export SLEEP_TIME=0
          export NUM_OF_LOOPS=1 
          export TOTAL_NUM_OF_CALLS=10 
          export RECURSION_DEPTH=10 
          ./benchmark.sh 
          unzip results-OpenTelemetry-java/results.zip 
          measuredValues=$(cat raw-1-10-* | wc -l) 
          if [ $measuredValues -ne 50 ] 
          then
            echo "It should be 50 measured values, but was $measuredValues"
            exit 1
          fi

